"""
tools/scaffolding.py
Generates a standardized, Cookiecutter-Data-Science-style project layout
(data/raw, data/processed, notebooks/, src/, models/, reports/, ...) with
a tailored requirements.txt and .gitignore.
"""
from __future__ import annotations

from pathlib import Path

_REQUIREMENTS = """\
pandas
polars
numpy
scikit-learn
matplotlib
seaborn
duckdb
jupyter
pytest
python-dotenv
"""

_GITIGNORE = """\
__pycache__/
*.pyc
.env
.venv/
venv/
data/raw/*
data/processed/*
!data/raw/.gitkeep
!data/processed/.gitkeep
models/*
!models/.gitkeep
.ipynb_checkpoints/
*.duckdb
.DS_Store
"""

_DIRS = [
    "data/raw", "data/processed", "data/external", "data/interim",
    "notebooks", "src", "models", "reports/figures", "tests",
]


def scaffold_project(project_name: str, base_dir: str = ".") -> str:
    """Create a Cookiecutter-DS-style folder structure for `project_name`
    under `base_dir`, plus a requirements.txt, .gitignore, and README."""
    safe_name = project_name.strip().replace(" ", "_")
    if not safe_name:
        return "Please provide a non-empty project name."

    root = Path(base_dir).resolve() / safe_name
    if root.exists():
        return f"Directory '{root}' already exists; choose a different name or location."

    for rel in _DIRS:
        target = root / rel
        target.mkdir(parents=True, exist_ok=True)
        if not any(target.iterdir()):
            (target / ".gitkeep").touch()

    (root / "requirements.txt").write_text(_REQUIREMENTS)
    (root / ".gitignore").write_text(_GITIGNORE)
    (root / "README.md").write_text(f"# {safe_name}\n\nGenerated by the JARVIS DS/BI Assistant.\n")
    (root / "src" / "__init__.py").touch()

    tree = "\n".join(f"  {safe_name}/{d}/" for d in _DIRS)
    return (
        f"Project scaffolded at {root}\n\n{tree}\n"
        f"  {safe_name}/requirements.txt\n  {safe_name}/.gitignore\n  {safe_name}/README.md"
    )
