import pyttsx3
import speech_recognition as sr
import threading
import queue
import datetime
import os
import sys
import io
import duckdb
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

class VoiceDataScienceJARVIS:
    """
    JARVIS: Voice-Enabled Data Science, Analytics, & BI Assistant
    """
    
    def __init__(self):
        self.tts_engine = pyttsx3.init()
        self.tts_engine.setProperty('rate', 165)
        self.tts_queue = queue.Queue()
        
        self.tts_thread = threading.Thread(target=self._tts_worker, daemon=True)
        self.tts_thread.start()

        self.name = "JARVIS"
        self.running = True
        self.db_conn = duckdb.connect(database=':memory:')

        try:
            self.recognizer = sr.Recognizer()
            self.microphone = sr.Microphone()
            self.has_mic = True
        except (AttributeError, Exception):
            print("⚠️ Microphone unavailable (PyAudio missing). Running in Hybrid Text-Voice mode.")
            self.has_mic = False

    def _tts_worker(self):
        while True:
            text = self.tts_queue.get()
            if text is None:
                break
            self.tts_engine.say(text)
            self.tts_engine.runAndWait()
            self.tts_queue.task_done()

    def speak(self, text: str):
        print(f"\n🤖 {self.name}: {text}\n")
        self.tts_queue.put(text)

    def listen(self) -> str:
        if not getattr(self, 'has_mic', False):
            return input("\n👤 You (Text Mode): ")
            
        with self.microphone as source:
            print("\n🎙️ Listening...")
            self.recognizer.adjust_for_ambient_noise(source, duration=0.8)
            try:
                audio = self.recognizer.listen(source, timeout=5, phrase_time_limit=10)
                print("⚡ Processing speech...")
                command = self.recognizer.recognize_google(audio)
                print(f"👤 You said: {command}")
                return command
            except Exception:
                return input("\n👤 Voice missed. Type command: ")

    def run_python_code(self, code: str) -> str:
        old_stdout = sys.stdout
        sys.stdout = output_buffer = io.StringIO()
        try:
            exec(code, globals())
            sys.stdout = old_stdout
            result = output_buffer.getvalue()
            return result if result else "Execution finished with no output."
        except Exception as e:
            sys.stdout = old_stdout
            return f"Execution Error: {str(e)}"

    def execute_sql(self, query: str) -> str:
        try:
            df = self.db_conn.execute(query).df()
            return f"Query Results:\n{df.head(5).to_string()}"
        except Exception as e:
            return f"SQL Error: {str(e)}"

    def create_project_scaffold(self, project_name: str) -> str:
        dirs = [
            f"{project_name}/data/raw",
            f"{project_name}/data/processed",
            f"{project_name}/notebooks",
            f"{project_name}/src",
            f"{project_name}/models",
            f"{project_name}/reports"
        ]
        for d in dirs:
            os.makedirs(d, exist_ok=True)
            
        with open(f"{project_name}/requirements.txt", "w", encoding="utf-8") as f:
            f.write("pandas\npolars\nnumpy\nscikit-learn\nduckdb\nmatplotlib\nseaborn\nstreamlit\npython-dotenv\n")

        with open(f"{project_name}/README.md", "w", encoding="utf-8") as f:
            f.write(f"# {project_name.replace('_', ' ').title()}\n\nAutomated Data Science & BI analytics workspace generated by JARVIS.\n")

        with open(f"{project_name}/src/data_loader.py", "w", encoding="utf-8") as f:
            f.write('''import pandas as pd
import duckdb

def load_data(file_path: str) -> pd.DataFrame:
    print(f"Loading dataset from {file_path}...")
    return duckdb.query(f"SELECT * FROM '{file_path}'").df()

if __name__ == "__main__":
    print("Data Loader script ready.")
''')

        starter_notebook = '''{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Exploratory Data Analysis\\n",
    "Generated automatically by **JARVIS DS Agent**."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\\n",
    "import duckdb\\n",
    "import matplotlib.pyplot as plt\\n",
    "import seaborn as sns\\n",
    "\\n",
    "print('DS Libraries Loaded Successfully')"
   ]
  }
 ],
 "metadata": {
  "language_info": { "name": "python" }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}'''
        with open(f"{project_name}/notebooks/01_eda.ipynb", "w", encoding="utf-8") as f:
            f.write(starter_notebook)

        with open(f"{project_name}/src/app.py", "w", encoding="utf-8") as f:
            f.write('''import streamlit as st
import pandas as pd
import duckdb

st.set_page_config(page_title="Analytics Dashboard", layout="wide")
st.title("📊 Business Intelligence Dashboard")

st.info("Generated by JARVIS. Load your datasets to start visualizing metrics.")
''')

        return f"Created populated DS project workspace for '{project_name}' with starter scripts, notebooks, and dashboard boilerplate."

    def process_command(self, command: str):
        if not command:
            return
            
        cmd_clean = command.strip()
        cmd_lower = cmd_clean.lower()

        if any(w in cmd_lower for w in ["hello", "hi", "hey"]):
            self.speak("Systems operational. Ready for data commands.")

        elif "run python" in cmd_lower or "execute code" in cmd_lower:
            code = cmd_clean.split("code")[-1].replace("run python", "").strip()
            if code:
                self.speak("Running Python code.")
                res = self.run_python_code(code)
                print(res)
            else:
                self.speak("Please state or provide the code snippet to execute.")

        elif "sql" in cmd_lower or "query" in cmd_lower:
            query = cmd_clean.split("query")[-1].replace("sql", "").strip()
            if query:
                self.speak("Executing SQL query.")
                res = self.execute_sql(query)
                print(res)
            else:
                self.speak("Please state the SQL query.")

        elif "create project" in cmd_lower or "scaffold project" in cmd_lower:
            name = cmd_clean.split("project")[-1].replace(":", "").strip() or "ds_analytics_project"
            res = self.create_project_scaffold(name)
            self.speak(res)

        elif any(w in cmd_lower for w in ["shutdown", "exit", "goodbye", "quit"]):
            self.speak("Shutting down workspace interface. Goodbye.")
            self.running = False

        elif "help" in cmd_lower:
            self.speak("You can tell me to create a project, run SQL queries, or execute Python code.")

        else:
            self.speak("Command not recognized. Say help for commands.")

    def run(self):
        print("=" * 60)
        print("🤖 JARVIS - DATA SCIENCE & BI ENGINE")
        print("=" * 60)
        self.speak("JARVIS DS/BI Engine ready.")
        
        while self.running:
            try:
                command = self.listen()
                if command:
                    self.process_command(command)
            except KeyboardInterrupt:
                self.speak("Emergency shutdown initiated.")
                self.running = False
                
        self.tts_queue.put(None)

if __name__ == "__main__":
    jarvis = VoiceDataScienceJARVIS()
    jarvis.run()