import streamlit as st
import pandas as pd
import duckdb

st.set_page_config(page_title="Analytics Dashboard", layout="wide")
st.title("📊 Business Intelligence Dashboard")

st.info("Generated by JARVIS. Load your datasets to start visualizing metrics.")
